---
- name: List all Networks in the Meraki Organization
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Get Organization Networks
      cisco.meraki.networks_info:
        organizationId: "{{ org_id }}"
      register: network_list

    - name: Print the list of networks
      ansible.builtin.debug:
        msg: "{{ network_list }}"
