---
- name: Configure Meraki SSID with Dot1x
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Create corporate SSID
      cisco.meraki.networks_wireless_ssids:
        state: present
        enabled: true
        name: "{{corp_name}}"
        networkId: "{{ network_id }}"
        number: 0
        ipAssignmentMode: Bridge mode
        defaultVlanId: 100
        useVlanTagging: true
        authMode: "8021x-radius"
        wpaEncryptionMode: WPA2 only
        radiusServers: "{{radius_servers}}"
    
