---
- name: Configure VLANs
  hosts: cat_switches
  gather_facts: false
  collections:
    - cisco.ios
  tasks:

    - name: add vlans
      ios_vlans:
        config: "{{ vlans }}"
        state: merged