- name: Configure Dot1x Auth
  hosts: cat_switches
  gather_facts: no
  collections:
    - cisco.ios
  tasks:

    - name: Config AAA
      ios_config:
        lines:
          - dot1x system-auth-control
          - aaa new-model
          - aaa authentication dot1x default group radius
          - ip radius source-interface GigabitEthernet0/0

    - name: Config Radius
      ios_config:
        lines:
          - address ipv4 {{radius_server1}}
        parents: radius server ise1

    - name: Config infs
      ios_config:
        lines:
          - dot1x port-control auto
        parents: "interface {{ item }}"
      loop: "{{LP_intfs + POS_intfs}}"