---
- name: Configure L2 interfaces
  hosts: cat_switches
  gather_facts: false
  tasks:

    - name: Configure AP interfaces
      cisco.ios.ios_l2_interfaces:
        config: "{{ AP_intf_conf }}"
        state: replaced
      loop: "{{ AP_intfs }}"

    - name: Configure LP interfaces
      cisco.ios.ios_l2_interfaces:
        config: "{{ LP_intf_conf }}"
        state: replaced
      loop: "{{ LP_intfs }}"

    - name: Configure POS interfaces
      cisco.ios.ios_l2_interfaces:
        config: "{{ POS_intf_conf }}"
        state: replaced
      loop: "{{ POS_intfs }}"
