---
- name: Connect vpn to DevNet Sandbox
  hosts: localhost
  connection: local

  vars_prompt:
    - name: pod_num
      prompt: What is your assigned lab number?
      private: no

  tasks:
    - name: Fail if a setting is missing
      fail:
        msg: "Please answer all user prompts with valid values"
      when: pod_num == ""

    - name: Read in file
      shell: cat devwks-2301-clus25.csv
      register: pods

    - name: Set creds
      set_fact:
        pod_line: "{{ pods.stdout_lines[pod_num | int].split(',') }}"

    - name: Set user
      set_fact:
        pod_user: "{{ pod_line[3] }}"

    - name: Set Password
      set_fact:
        pod_pass: "{{ pod_line[4] }}"

    - name: Set Endpoint Port
      set_fact:
        pod_port: "{{ pod_line[1] }}"

    - name: Set Meraki API Key
      set_fact:
        api_key: "{{ pod_line[5] }}"

    - name: Export Meraki API Key
      shell: "export 'MERAKI_DASHBOARD_API_KEY={{api_key}}'"

    - name: Print User Message 
      debug:
        msg: "You are now connected to VPN and your Meraki API key has been stored, please open a new tab"

    - name: "Connecting VPN"
      # shell: "sudo openconnect devnetsandbox-usw1-reservation.cisco.com:{{pod_port}} -b --no-dtls -q -u {{pod_user}} < vpnpw.txt"
      # shell: "sudo openconnect devnetsandbox-usw1-reservation.cisco.com:{{pod_port}} --no-dtls  -u {{pod_user}} < vpnpw.txt"
      # shell: "echo {{pod_pass}} | sudo openconnect devnetsandbox-usw1-reservation.cisco.com:{{pod_port}} --no-dtls  -u {{pod_user}} --passwd-on-stdin"
      shell: "echo {{pod_pass}} | sudo openconnect {{pod_port}} -v --no-dtls -u {{pod_user}} --passwd-on-stdin"