- name: Testing our fact-finding mission
  hosts: cat_switches
  gather_facts: no

  tasks:

  - name: Gather IOSXE Facts
    cisco.ios.ios_facts:
      gather_subset:
      - config
    when: ansible_network_os == 'cisco.ios.ios'
      
  - name: print facts
    debug:
      msg: "{{ansible_net_config}}"